### ISSUE TITLE
¿Cuántas veces lo abres y lo dejas abierto? Crea la clase Teclado, envoltorio de este Scanner

### ISSUE THREAD

**Issue by lmagarin** [front440/JAVA#5]
https://github.com/front440/GESTISIMAL/blob/5e54d968c2bc43c14422b03a2aa2535caf98d53d/TestAlmacen.java#L80

**Comment by front440** [comment]
Problema Resuelto en issue #6 .
Implementado en la clase teclado dentro del paquete utiles

**Comment by lmagarin** [comment]
Necesito UN ÚNICO REPOSITORIO SÓLO CON ESTA ENTREGA.
